name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install IPFS
      run: |
        wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
        tar -xvzf go-ipfs_v0.11.0_linux-amd64.tar.gz
        sudo mv go-ipfs/ipfs /usr/local/bin/ipfs

    - name: Configure IPFS
      run: ipfs init

    - name: Add files to IPFS
      run: |
        ipfs add -r .

    - name: Upload to Pinata
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
      run: |
        curl -H "Authorization: Bearer $PINATA_API_KEY:$PINATA_SECRET_KEY" \
             -F "file=@./QmHash" \
             -F "wrapWithDirectory=true" \
             -F "pinataMetadata={\"name\":\"IPFS Demo\"}" \
             https://api.pinata.cloud/pinning/pinFileToIPFS
